#!/usr/bin/env python3
"""Fill gitdesk_en.ts English translations and mark finished. UTF-8."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TS = ROOT / "i18n" / "gitdesk_en.ts"

# source (zh or en as in QML) -> English
EN: dict[str, str] = {
    # Common
    "打开仓库": "Open repository",
    "克隆仓库": "Clone repository",
    "设置": "Settings",
    "刷新": "Refresh",
    "Fetch": "Fetch",
    "Pull": "Pull",
    "Push": "Push",
    "Stash": "Stash",
    "Stash Pop": "Stash Pop",
    "丢弃全部未暂存": "Discard all unstaged",
    "新建标签": "New tag",
    "概览": "Overview",
    "图谱": "Graph",
    "变更": "Changes",
    "历史": "History",
    "新建分支": "New branch",
    "Overview": "Overview",
    "Graph": "Graph",
    "Changes": "Changes",
    "History": "History",
    "GitDesk": "GitDesk",
    "GitDesk — %1": "GitDesk — %1",
    "详情": "Detail",
    "创建分支": "Create branch",
    "基于当前 HEAD 创建新分支": "Create a new branch from current HEAD",
    "创建": "Create",
    "取消": "Cancel",
    "分支名": "Branch name",
    "在当前 HEAD 上创建标签": "Create a tag on current HEAD",
    "标签名": "Tag name",
    "说明（可选，有说明则为 annotated）": "Message (optional; annotated if set)",
    "Release notes…": "Release notes…",
    "删除标签？": "Delete tag?",
    "将删除本地标签 %1": "Delete local tag %1",
    "删除": "Delete",
    "保存当前工作区变更（含未跟踪文件）": "Save working tree changes (including untracked)",
    "说明（可选）": "Message (optional)",
    "WIP…": "WIP…",
    "保存": "Save",
    "丢弃文件变更？": "Discard file changes?",
    "将丢弃未暂存变更：%1": "Discard unstaged changes in: %1",
    "丢弃": "Discard",
    "丢弃全部未暂存？": "Discard all unstaged?",
    "将还原所有已跟踪文件的未暂存修改（不影响已暂存与未跟踪文件）。":
        "Restore unstaged changes in tracked files (staged and untracked files are untouched).",
    "丢弃全部": "Discard all",
    "输入远程地址，并选择本地目标文件夹路径": "Enter the remote URL and local destination path",
    "克隆": "Clone",
    "仓库 URL": "Repository URL",
    "目标目录（完整路径）": "Destination directory (full path)",
    "选择父目录…": "Choose parent folder…",
    "完成": "Done",
    "Ctrl+O 打开仓库": "Ctrl+O Open repository",
    "%1 · %2 changes": "%1 · %2 changes",
    "%1 · ↑%2 ↓%3 · %4 changes": "%1 · ↑%2 ↓%3 · %4 changes",
    "↑%1 ↓%2": "↑%1 ↓%2",
    "打开": "Open",
    "Branch": "Branch",
    "新建分支…": "New branch…",
    "Commit": "Commit",
    "Repository": "Repository",
    "PROJECT": "PROJECT",
    "Branches": "Branches",
    "Remote": "Remote",
    "Tags": "Tags",
    "无本地分支": "No local branches",
    "无远程": "No remotes",
    "无标签": "No tags",
    "Staged": "Staged",
    "Unstaged": "Unstaged",
    "Stashes": "Stashes",
    "Stash · %1": "Stash · %1",
    "Pop": "Pop",
    "工作区干净": "Clean working tree",
    "没有未提交的变更": "No uncommitted changes",
    "暂存文件后填写说明": "Write a message after staging files",
    "Commit Message": "Commit message",
    "简述本次变更…": "Summarize this change…",
    "Amend": "Amend",
    "Stage All": "Stage all",
    "Amend Commit": "Amend commit",
    "Author": "Author",
    "Date": "Date",
    "Message": "Message",
    "Copy SHA": "Copy SHA",
    "已复制": "Copied",
    "File": "File",
    "Diff": "Diff",
    "Inline": "Inline",
    "Split": "Split",
    "加载 Diff…": "Loading Diff…",
    "无 Diff": "No Diff",
    "选择变更文件或 Commit": "Select a changed file or commit",
    "把 Git 变成可操作的软件工程地图": "Turn Git into a visual engineering map",
    "最近打开": "Recently opened",
    "初始化仓库": "Initialize repository",
    "语言": "Language",
    "界面语言": "UI language",
    "外观": "Appearance",
    "主题与密度": "Theme and density",
    "深色模式": "Dark mode",
    "紧凑密度（IDE）": "Compact density (IDE)",
    "显示键盘焦点环": "Show keyboard focus rings",
    "主题色 Seed": "Theme seed color",
    "工作区": "Workspace",
    "面板与 Diff": "Panels and Diff",
    "打开仓库时显示详情面板": "Show detail panel when opening a repo",
    "Diff 显示行号": "Show Diff line numbers",
    "提交模板与可执行文件": "Commit template and executable",
    "Commit 模板": "Commit template",
    "例如：feat: ": "e.g. feat: ",
    "git 路径（可选，留空则自动查找）": "git path (optional, auto-detect if empty)",
    "当前仓库：%1": "Current repository: %1",
    "当前未打开仓库": "No repository open",
    "数据": "Data",
    "最近仓库": "Recent repositories",
    "最近打开 %1 个仓库": "%1 recent repositories",
    "清空最近列表": "Clear recent list",
    "快捷键": "Shortcuts",
    "全局": "Global",
    "命令面板": "Command palette",
    "提交（有 message 时）": "Commit (when message is set)",
    "关于": "About",
    "偏好设置": "Preferences",
    "设置已保存": "Settings saved",
    "关闭": "Close",
    "清空最近仓库？": "Clear recent repositories?",
    "将清除欢迎页上的最近打开列表。": "This clears the recent list on the welcome page.",
    "清空": "Clear",
    "已清空": "Cleared",
    "渠道 %1 · %2": "Channel %1 · %2",
    "History · %1": "History · %1",
    "搜索提交…": "Search commits…",
    "最近活动": "Recent activity",
    "暂无提交记录": "No commits yet",
    "Push 并设置上游": "Push and set upstream",
    "初始化 Git 仓库": "Initialize Git repository",
    "在选定文件夹中执行 git init 并打开": "Run git init in the chosen folder and open it",
    "已暂存": "Staged",
    "未暂存": "Unstaged",
    "贮藏": "Stash",
    "贮藏 · %1": "Stash · %1",
    "弹出": "Pop",
    "提交": "Commit",
    "提交说明": "Commit message",
    "修正上次提交": "Amend last commit",
    "全部暂存": "Stage all",
    "修正提交": "Amend commit",
    "分支": "Branch",
    "推送上游": "Push upstream",
    "仓库": "Repository",
    "项目": "Project",
    "远程": "Remote",
    "标签": "Tags",
    "历史 · %1": "History · %1",
    "贡献者": "Contributors",
    "作者": "Author",
    "日期": "Date",
    "说明": "Message",
    "复制 SHA": "Copy SHA",
    "文件": "File",
    "暂存": "Stage",
    "取消暂存": "Unstage",
    "选择提交或文件": "Select a commit or file",
    "在图谱 / 变更 / 历史中点击条目": "Click an item in Graph / Changes / History",
    "差异": "Diff",
    "单栏": "Inline",
    "分栏": "Split",
    "无差异": "No Diff",
    "选择变更文件或提交": "Select a changed file or commit",
    "加载差异…": "Loading Diff…",
    "差异已复制": "Diff copied",
    "获取": "Fetch",
    "拉取": "Pull",
    "推送": "Push",
    "弹出贮藏": "Pop stash",
    "贮藏": "Stash",
    "请等待当前操作完成": "Please wait for the current operation",
    "正在打开仓库…": "Opening repository…",
    "无法打开仓库": "Could not open repository",
    "已打开仓库": "Repository opened",
    "正在刷新…": "Refreshing…",
    "刷新失败": "Refresh failed",
    "正在 Fetch…": "Fetching…",
    "Fetch 失败": "Fetch failed",
    "Fetch 完成": "Fetch complete",
    "正在 Pull…": "Pulling…",
    "Pull 失败": "Pull failed",
    "Pull 完成": "Pull complete",
    "正在 Push…": "Pushing…",
    "Push 失败": "Push failed",
    "Push 完成": "Push complete",
    "正在 Push 并设置上游…": "Pushing and setting upstream…",
    "已推送并设置上游": "Pushed and upstream set",
    "Staging…": "Staging…",
    "Stage 失败": "Stage failed",
    "Unstaging…": "Unstaging…",
    "Unstage 失败": "Unstage failed",
    "已取消暂存": "Unstaged",
    "Staging all…": "Staging all…",
    "Stage all 失败": "Stage all failed",
    "已全部暂存": "All staged",
    "Unstaging all…": "Unstaging all…",
    "Unstage all 失败": "Unstage all failed",
    "已全部取消暂存": "All unstaged",
    "丢弃变更…": "Discarding…",
    "丢弃失败": "Discard failed",
    "已丢弃 %1": "Discarded %1",
    "丢弃全部未暂存…": "Discarding all unstaged…",
    "已丢弃未暂存变更": "Unstaged changes discarded",
    "Stash…": "Stashing…",
    "Stash 失败": "Stash failed",
    "已保存 Stash": "Stash saved",
    "Stash Pop…": "Popping stash…",
    "Stash Pop 失败": "Stash pop failed",
    "已弹出 Stash": "Stash popped",
    "删除 Stash…": "Dropping stash…",
    "删除 Stash 失败": "Drop stash failed",
    "已删除 Stash": "Stash dropped",
    "正在提交…": "Committing…",
    "提交失败": "Commit failed",
    "提交成功": "Commit succeeded",
    "切换分支…": "Switching branch…",
    "切换失败": "Checkout failed",
    "已切换到 %1": "Switched to %1",
    "创建分支…": "Creating branch…",
    "创建失败": "Create failed",
    "已创建 %1": "Created %1",
    "删除分支…": "Deleting branch…",
    "删除失败": "Delete failed",
    "已删除 %1": "Deleted %1",
    "Merge…": "Merging…",
    "Merge 失败": "Merge failed",
    "已合并 %1": "Merged %1",
    "创建标签…": "Creating tag…",
    "创建标签失败": "Create tag failed",
    "已创建标签 %1": "Created tag %1",
    "删除标签…": "Deleting tag…",
    "删除标签失败": "Delete tag failed",
    "已删除标签 %1": "Deleted tag %1",
    "请填写克隆地址与目标目录": "Please enter clone URL and destination",
    "正在克隆…": "Cloning…",
    "克隆失败": "Clone failed",
    "克隆完成": "Clone complete",
    "选择克隆目标父目录": "Choose clone parent folder",
    "正在初始化仓库…": "Initializing repository…",
    "初始化失败": "Init failed",
    "仓库已初始化": "Repository initialized",
    "选择要初始化的文件夹": "Choose folder to initialize",
    "作者：%1": "Author: %1",
    "Open a repository to begin": "Open a repository to begin",
    "No repository open": "No repository open",
    "Open Git Repository": "Open Git Repository",
    "%1 · %2 · %3 changes": "%1 · %2 · %3 changes",

    # 0.2.x–0.3.0 strong ops / conflict / blame / compare
    "渠道 %1 · %2": "Channel %1 · %2",
    "更新日志": "Changelog",
    "作者：%1": "Author: %1",
    "Rebase 进行中 · %1 个冲突": "Rebase in progress · %1 conflict(s)",
    "合并进行中 · %1 个冲突": "Merge in progress · %1 conflict(s)",
    "%1 个冲突文件": "%1 conflicted file(s)",
    "继续": "Continue",
    "中止": "Abort",
    "采用我们的": "Take ours",
    "采用他们的": "Take theirs",
    "从此创建分支…": "Create branch from here…",
    "Cherry-pick": "Cherry-pick",
    "Revert": "Revert",
    "Reset Soft": "Reset Soft",
    "Reset Mixed": "Reset Mixed",
    "Reset Hard": "Reset Hard",
    "显示 Blame": "Show Blame",
    "Blame（最多 2000 行）": "Blame (up to 2000 lines)",
    "文件历史": "File history",
    "分支对比": "Branch compare",
    "%1 → %2 · 超前 %3 · 落后 %4": "%1 → %2 · ahead %3 · behind %4",
    "正在 Pull --rebase…": "Pulling with --rebase…",
    "Pull --rebase 失败": "Pull --rebase failed",
    "Pull --rebase 完成": "Pull --rebase complete",
    "Revert…": "Reverting…",
    "Revert 失败": "Revert failed",
    "已 Revert %1": "Reverted %1",
    "Cherry-pick…": "Cherry-picking…",
    "Cherry-pick 失败": "Cherry-pick failed",
    "已 Cherry-pick %1": "Cherry-picked %1",
    "Reset…": "Resetting…",
    "Reset 失败": "Reset failed",
    "已 Reset (%1) 到 %2": "Reset (%1) to %2",
    "当前未打开仓库": "No repository open",
    "无法打开文件夹": "Could not open folder",
    "远程 URL 为空": "Remote URL is empty",
    "无法打开远程链接": "Could not open remote URL",
    "中止合并…": "Aborting merge…",
    "中止合并失败": "Abort merge failed",
    "已中止合并": "Merge aborted",
    "中止 Rebase…": "Aborting rebase…",
    "中止 Rebase 失败": "Abort rebase failed",
    "已中止 Rebase": "Rebase aborted",
    "继续 Rebase…": "Continuing rebase…",
    "继续 Rebase 失败": "Continue rebase failed",
    "Rebase 已继续": "Rebase continued",
    "解决冲突…": "Resolving conflict…",
    "解决冲突失败": "Resolve conflict failed",
    "已采用 %1：%2": "Took %1: %2",
    "对比分支…": "Comparing branches…",
    "分支对比完成": "Branch compare complete",
    "拉取 --rebase": "Pull --rebase",
    "对比分支": "Compare branches",
    "打开文件夹": "Open folder",
    "中止合并": "Abort merge",
    "继续 Rebase": "Continue rebase",
    "中止 Rebase": "Abort rebase",
    "关闭仓库": "Close repository",
    "%1 · Rebase · 冲突 %2 · %3 changes": "%1 · Rebase · conflicts %2 · %3 changes",
    "%1 · 冲突 %2 · %3 changes": "%1 · conflicts %2 · %3 changes",
    "基于提交 %1 创建新分支": "Create a new branch from commit %1",
    "Revert 提交？": "Revert commit?",
    "将创建一次新提交，撤销 %1 的变更。": "Creates a new commit that undoes changes from %1.",
    "Cherry-pick？": "Cherry-pick?",
    "将把提交 %1 应用到当前分支。": "Applies commit %1 onto the current branch.",
    "Reset 到提交？": "Reset to commit?",
    "Soft：移动 HEAD 到 %1，保留暂存区与工作区。": "Soft: move HEAD to %1; keep index and working tree.",
    "Hard：移动 HEAD 到 %1，并丢弃暂存区与工作区变更。": "Hard: move HEAD to %1; discard index and working tree changes.",
    "Mixed：移动 HEAD 到 %1，保留工作区，清空暂存区。": "Mixed: move HEAD to %1; keep working tree, reset index.",
    "Reset": "Reset",
    "查看 head 相对 base 多出的提交": "Show commits on head that are not in base",
    "对比": "Compare",
    "Base（对照）": "Base (reference)",
    "Head（当前侧）": "Head (current side)",
    "当前分支": "Current branch",
    "本地分支：%1": "Local branches: %1",
    "已复制远程 URL": "Remote URL copied",
    "拉取 (ff-only)": "Pull (ff-only)",
    "文件夹": "Folder",
}


def fill_ts(text: str) -> str:
    def repl(m: re.Match[str]) -> str:
        block = m.group(0)
        src_m = re.search(r"<source>(.*?)</source>", block, re.DOTALL)
        if not src_m:
            return block
        source = src_m.group(1)
        # unescape basic XML entities for lookup
        key = (
            source.replace("&lt;", "<")
            .replace("&gt;", ">")
            .replace("&amp;", "&")
            .replace("&quot;", '"')
            .replace("&apos;", "'")
        )
        en = EN.get(key)
        if en is None:
            # English source: keep as-is
            if all(ord(c) < 128 for c in key) or key.startswith("%"):
                en = key
            else:
                return block  # leave unfinished
        # escape for XML
        en_xml = (
            en.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
        )
        return re.sub(
            r"<translation[^>]*>.*?</translation>",
            f"<translation>{en_xml}</translation>",
            block,
            count=1,
            flags=re.DOTALL,
        )

    return re.sub(r"<message>.*?</message>", repl, text, flags=re.DOTALL)


def main() -> None:
    raw = TS.read_text(encoding="utf-8")
    out = fill_ts(raw)
    TS.write_text(out, encoding="utf-8", newline="\n")
    unfinished = out.count('type="unfinished"')
    print(f"Wrote {TS}; unfinished left: {unfinished}")


if __name__ == "__main__":
    main()
